/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

import org.junit.jupiter.api.Test;

import junit.framework.Assert;
import project.definition.TweetHashTag;

import java.util.Arrays; 
import java.util.List; 

class TweetHashTagGraphTest {
    @Test
    void testExtractHashTagsInAllTweets() {
        
        List<TweetHashTag> tweetHashTags = Arrays.asList( 
            new TweetHashTag("tweet1", Arrays.asList("gretel", "data")),
            new TweetHashTag("tweet2", Arrays.asList("data", "startup", "privacy")),
            new TweetHashTag("tweet3", Arrays.asList("data")),
            new TweetHashTag("tweet4", Arrays.asList("gretel")),
            new TweetHashTag("tweet5", Arrays.asList("rocketship", "gretel")),
            new TweetHashTag("tweet6", Arrays.asList("cats", "cats", "cats"))
        );
        TweetHashTagGraph graph = new TweetHashTagGraph();
        graph.createGraph(tweetHashTags);
        Assert.assertEquals(graph.getNumberOfEdges(), 10);
        Assert.assertEquals(graph.getNumberOfNodesInGraph(), 6);
    }
}
