/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.util.Optional;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpServer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println("COming to MAIN CLASSS !  " + System.getProperty("user.dir"));
        Engine engine = new Engine();
        engine.test();
    }

    public static void testWithHttpServer() throws IOException {
        int port = 8081;
        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/file/", new MyHandler());
        server.start();
        System.out.println("Server started at http://localhost:" + port);
    }

    static class MyHandler implements HttpHandler {

        public void sendResponse(String response, HttpExchange t) throws IOException {
            t.sendResponseHeaders(200, response.length());
            OutputStream os = t.getResponseBody();
            os.write(response.getBytes());
            os.close();
        }

        @Override
        public void handle(HttpExchange t) throws IOException {
            Engine engine = new Engine();
            double avg = engine.test();
            String response = System.currentTimeMillis() + " ) This is the average : " + avg;
            sendResponse(response, t);
        }

    }
}
