/*
 * This source file was generated by the Gradle 'init' task
 */
package project;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.util.Optional;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpServer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println("COming to MAIN CLASSS !  " + System.getProperty("user.dir"));
        Engine engine = new Engine();
        engine.calculateAverage();

        engine.addTweet("{\"id_str\":\"tweet11\",\"entities\":{\"hashtags\":[{\"text\":\"Gretel\"},{\"text\":\"data\"}]}}");
        System.out.println( "ADded tweet 11");
        engine.calculateAverage();
        
        engine.addTweet("{\"id_str\":\"tweet12\",\"entities\":{\"hashtags\":[{\"text\":\"dogs\"},{\"text\":\"tiger\"}]}}");
        System.out.println( "ADded tweet 12");
        engine.calculateAverage();

        engine.addTweet("{\"id_str\":\"tweet13\",\"entities\":{\"hashtags\":[{\"text\":\"dogs\"},{\"text\":\"tiger\"}]}}");
        System.out.println( "ADded tweet 13");
        engine.calculateAverage();

        engine.removeTweet("{\"id_str\":\"tweet13\",\"entities\":{\"hashtags\":[{\"text\":\"dogs\"},{\"text\":\"tiger\"}]}}");
        System.out.println( "Removed tweet 13");
        engine.calculateAverage();

        engine.removeTweet("{\"id_str\":\"tweet12\",\"entities\":{\"hashtags\":[{\"text\":\"dogs\"},{\"text\":\"tiger\"}]}}");
        System.out.println( "Removed tweet 12");
        engine.calculateAverage();

        engine.removeTweet("{\"id_str\":\"tweet1\",\"entities\":{\"hashtags\":[{\"text\":\"Gretel\"},{\"text\":\"data\"}]}}");
        System.out.println( "Removed tweet 1");
        engine.calculateAverage();

    
        engine.removeTweet("{\"id_str\":\"tweet7\",\"entities\":{\"hashtags\":[{\"text\":\"Gretel\"},{\"text\":\"data\"}]}}");
        System.out.println( "Removed tweet 7");
        engine.calculateAverage();

    }
}
